name: GitHub CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: 'bash -o errexit -o nounset -o pipefail {0}'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 2.5.23
          - 3.0.19
          - 4.0.15
#          - 5.0.0-alpha-2
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: jdk setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          java-package: jdk
          architecture: x64
      - name: unit and integration tests
        env:
          version: ${{ matrix.version }}
        run: |
          majorVersion=$(echo "${version}" | grep --extended-regex --only-matching "^[0-9]+")
          [ "${majorVersion}" -gt "3" ] && groupId="org.apache.groovy" || groupId="org.codehaus.groovy"
          ./mvnw --batch-mode -DgroovyVersion="${version}" -DgroovyGroupId="${groupId}" clean install invoker:install invoker:run
